<a href="https://colab.research.google.com/github/Hanniix22/BSC_DPDM2025/blob/main/midterm_663020039_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [16]:
hii_daily_rain = pd.read_csv('/content/drive/MyDrive/midtermdata/BSC DPDM midterm 2025/Daily rain - (Statistics 2012-2024)/hii_daily_rain.csv')
hii_daily_rain

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.664290,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3768458,YOM016,2024-11-25 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768459,YOM016,2024-11-26 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768460,YOM016,2024-11-27 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768461,YOM016,2024-11-28 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily
3768462,YOM016,2024-11-29 00:00:00+07,0.0,ห้วยแม่พวก,17.968712,100.063545,N,NaN,NaN,เด่นชัย,เด่นชัย,แพร่,rainfall_daily

In [22]:
import os
import pandas as pd

# Define the base path for the 2025 operational daily rain data
base_path = '/content/drive/MyDrive/midtermdata/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)'

# Create a dictionary to store DataFrames for each month
monthly_dfs = {}

# Loop through months from 7 (July) to 12 (December) for 2025
for month in range(7, 13):
    month_str = f'2025-{month:02d}' # Format month as '07', '08', etc.
    month_path = os.path.join(base_path, month_str)

    # Check if the directory exists
    if os.path.exists(month_path):
        all_daily_files = []
        # List all CSV files in the current month's directory
        for file_name in os.listdir(month_path):
            if file_name.endswith('.csv'):
                file_path = os.path.join(month_path, file_name)
                # Read each daily CSV file and append to a list
                all_daily_files.append(pd.read_csv(file_path))

        # Concatenate all daily DataFrames for the current month into one DataFrame
        if all_daily_files:
            monthly_dfs[f'df_2025_{month:02d}'] = pd.concat(all_daily_files, ignore_index=True)
            print(f"Loaded {len(all_daily_files)} daily files for {month_str} into df_2025_{month:02d}")
        else:
            print(f"No CSV files found in {month_path}")
    else:
        print(f"Directory not found: {month_path}")

# You can now access each monthly DataFrame, e.g., monthly_dfs['df_2025_07']
# To verify, print the first few rows of the July DataFrame if it exists
if 'df_2025_07' in monthly_dfs:
    print("\nFirst 5 rows of df_2025_07:")
    print(monthly_dfs['df_2025_07'].head())

Loaded 31 daily files for 2025-07 into df_2025_07
Loaded 32 daily files for 2025-08 into df_2025_08
Loaded 32 daily files for 2025-09 into df_2025_09
Loaded 31 daily files for 2025-10 into df_2025_10
Loaded 30 daily files for 2025-11 into df_2025_11
Loaded 31 daily files for 2025-12 into df_2025_12

First 5 rows of df_2025_07:
           rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
0  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.2
1  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.0
2  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             1.0
3  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.6
4  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.0

   tele_station_id tele_station_oldcode measure_datetime
0              447                 THCG       2025-07-10
1              812               TPI004       2025-07-10
2              669                 PPRM       2025-07-10
3              865               TNG002       2025-07-10
4              937                 PNCR       2025-07-10

In [24]:
monthly_dfs

{'df_2025_07':                rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
 0      2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.2
 1      2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.0
 2      2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             1.0
 3      2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.6
 4      2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.0
 ...                          ...                        ...             ...
 27870  2025-07-07 00:00:00+07:00  2025-07-07T07:00:00+07:00             0.0
 27871  2025-07-07 00:00:00+07:00  2025-07-07T07:00:00+07:00             0.0
 27872  2025-07-07 00:00:00+07:00  2025-07-07T07:00:00+07:00             3.0
 27873  2025-07-07 00:00:00+07:00  2025-07-07T07:00:00+07:00             1.6
 27874  2025-07-07 00:00:00+07:00  2025-07-07T07:00:00+07:00             0.0

        tele_station_id tele_station_oldcode measure_datetime
 0                  447                 THCG       2025-07-10
 1                  812               TPI004       2025-07-10
 2                  669                 PPRM       2025-07-10
 3                  865               TNG002       2025-07-10
 4                  937                 PNCR       2025-07-10
 ...                ...                  ...              ...
 27870               79               THA001       2025-07-06
 27871              326                 PHON       2025-07-06
 27872              550               CHR004       2025-07-06
 27873          1512927                  NaN       2025-07-06
 27874              187               NYK001       2025-07-06

 [27875 rows x 6 columns],
 'df_2025_08':                rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
 0      2025-08-25 00:00:00+07:00  2025-08-25T07:00:00+07:00             0.0
 1      2025-08-25 00:00:00+07:00  2025-08-25T07:00:00+07:00             0.0
 2      2025-08-25 00:00:00+07:00  2025-08-25T07:00:00+07:00             5.2
 3      2025-08-25 00:00:00+07:00  2025-08-25T07:00:00+07:00             0.0
 4      2025-08-25 00:00:00+07:00  2025-08-24T07:00:00+07:00             0.0
 ...                          ...                        ...             ...
 29178  2025-08-27 00:00:00+07:00  2025-08-27T07:00:00+07:00             1.2
 29179  2025-08-27 00:00:00+07:00  2025-08-27T07:00:00+07:00            15.6
 29180  2025-08-27 00:00:00+07:00  2025-08-27T07:00:00+07:00             0.0
 29181  2025-08-27 00:00:00+07:00  2025-08-27T07:00:00+07:00             0.0
 29182  2025-08-27 00:00:00+07:00  2025-08-27T07:00:00+07:00             4.8

        tele_station_id tele_station_oldcode measure_datetime station_code  \
 0                 25.0                 BKNH       2025-08-24          NaN
 1            1093079.0               CHAU01       2025-08-24          NaN
 2             492355.0               ATG111       2025-08-24          NaN
 3            1082427.0               CHK001       2025-08-24          NaN
 4                126.0                 BTCH       2025-08-24          NaN
 ...                ...                  ...              ...          ...
 29178         479235.0               TBW027       2025-08-26          NaN
 29179            748.0               THA008       2025-08-26          NaN
 29180         435372.0               TBR016       2025-08-26          NaN
 29181         457841.0               VLGE49       2025-08-26          NaN
 29182            364.0                 NOKG       2025-08-26          NaN

        value
 0        NaN
 1        NaN
 2        NaN
 3        NaN
 4        NaN
 ...      ...
 29178    NaN
 29179    NaN
 29180    NaN
 29181    NaN
 29182    NaN

 [29183 rows x 8 columns],
 'df_2025_09':                rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
 0      2025-10-01 00:00:00+07:00  2025-09-30T07:00:00+07:00             7.6
 1      2025-10-01 00:00:00+07:00  2025-09-30T07:00:00+07:00             3.6
 2      2025-10-01 00:00:00+07:00  2025-09-30T07:00:00+07:00             5.4
 3      2025-10-01 00:00:00+07:00  2025-09-30T07:00:00+07:00             7.0
 4      2025-10-01 00:00:00+07:00  2025-09-30T07:00:00+07:00             0.0
 ...                          ...                        ...             ...
 30337  2025-09-08 00:00:00+07:00  2025-09-08T07:00:00+07:00            13.6
 30338  2025-09-08 00:00:00+07:00  2025-09-08T07:00:00+07:00             1.8
 30339  2025-09-08 00:00:00+07:00  2025-09-08T07:00:00+07:00            13.6
 30340  2025-09-08 00:00:00+07:00  2025-09-08T07:00:00+07:00             0.2
 30341  2025-09-08 00:00:00+07:00  2025-09-08T07:00:00+07:00            12.0

        tele_station_id tele_station_oldcode measure_datetime station_code  \
 0            1373272.0                  NaN       2025-09-30          NaN
 1            1116457.0               GOT001       2025-09-30          NaN
 2                537.0               CHR001       2025-09-30          NaN
 3            1197836.0               CHR007       2025-09-30          NaN
 4                743.0                 KSKP       2025-09-30          NaN
 ...                ...                  ...              ...          ...
 30337            145.0                 BGBO       2025-09-07          NaN
 30338            532.0                 PONG       2025-09-07          NaN
 30339        1238679.0               MOU338       2025-09-07          NaN
 30340            461.0                 WGNA       2025-09-07          NaN
 30341            886.0               STH002       2025-09-07          NaN

        value
 0        NaN
 1        NaN
 2        NaN
 3        NaN
 4        NaN
 ...      ...
 30337    NaN
 30338    NaN
 30339    NaN
 30340    NaN
 30341    NaN

 [30342 rows x 8 columns],
 'df_2025_10':                rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
 0      2025-10-26 00:00:00+07:00  2025-10-25T07:00:00+07:00             0.0
 1      2025-10-26 00:00:00+07:00  2025-10-25T07:00:00+07:00             0.0
 2      2025-10-26 00:00:00+07:00  2025-10-25T07:00:00+07:00             0.0
 3      2025-10-26 00:00:00+07:00  2025-10-25T07:00:00+07:00             0.0
 4      2025-10-26 00:00:00+07:00  2025-10-25T07:00:00+07:00             4.8
 ...                          ...                        ...             ...
 29510  2025-10-13 00:00:00+07:00  2025-10-12T07:00:00+07:00            16.2
 29511  2025-10-13 00:00:00+07:00  2025-10-12T07:00:00+07:00             2.6
 29512  2025-10-13 00:00:00+07:00  2025-10-12T07:00:00+07:00            22.8
 29513  2025-10-13 00:00:00+07:00  2025-10-12T07:00:00+07:00             2.6
 29514  2025-10-13 00:00:00+07:00  2025-10-12T07:00:00+07:00             1.2

        tele_station_id tele_station_oldcode measure_datetime
 0              1198627               TRD006       2025-10-25
 1                  420                 MNDM       2025-10-25
 2                  345                 POCE       2025-10-25
 3              1198626               TRD005       2025-10-25
 4                  811                 KSOD       2025-10-25
 ...                ...                  ...              ...
 29510              163                 MKKB       2025-10-12
 29511              757                 BNPK       2025-10-12
 29512              130                 MMNY       2025-10-12
 29513               87                 WTSG       2025-10-12
 29514              857                 NPCT       2025-10-12

 [29515 rows x 6 columns],
 'df_2025_11':                rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
 0      2025-11-04 00:00:00+07:00  2025-11-03T07:00:00+07:00            10.8
 1      2025-11-04 00:00:00+07:00  2025-11-03T07:00:00+07:00            13.6
 2      2025-11-04 00:00:00+07:00  2025-11-03T07:00:00+07:00             0.2
 3      2025-11-04 00:00:00+07:00  2025-11-03T07:00:00+07:00             0.0
 4      2025-11-04 00:00:00+07:00  2025-11-03T07:00:00+07:00             0.2
 ...                          ...                        ...             ...
 31081  2025-11-23 00:00:00+07:00  2025-11-22T07:00:00+07:00             0.0
 31082  2025-11-23 00:00:00+07:00  2025-11-22T07:00:00+07:00            85.8
 31083  2025-11-23 00:00:00+07:00  2025-11-22T07:00:00+07:00             0.0
 31084  2025-11-23 00:00:00+07:00  2025-11-22T07:00:00+07:00           125.6
 31085  2025-11-23 00:00:00+07:00  2025-11-22T07:00:00+07:00             0.4

        tele_station_id tele_station_oldcode measure_datetime
 0              1109596               ONE107       2025-11-03
 1                  602                 NKYG       2025-11-03
 2              1106450               TCP004       2025-11-03
 3                  377                 BMOD       2025-11-03
 4              1109537               ONE048       2025-11-03
 ...                ...                  ...              ...
 31081          1601375                  NaN       2025-11-22
 31082              853                 KAOP       2025-11-22
 31083               97                 CMKK       2025-11-22
 31084              857                 NPCT       2025-11-22
 31085              820                 KHNI       2025-11-22

 [31086 rows x 6 columns],
 'df_2025_12':                rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
 0      2025-12-21 00:00:00+07:00  2025-12-20T07:00:00+07:00             0.0
 1      2025-12-21 00:00:00+07:00  2025-12-20T07:00:00+07:00             0.0
 2      2025-12-21 00:00:00+07:00  2025-12-20T07:00:00+07:00             0.0
 3      2025-12-21 00:00:00+07:00  2025-12-20T07:00:00+07:00             0.0
 4      2025-12-21 00:00:00+07:00  2025-12-20T07:00:00+07:00             0.0
 ...                          ...                        ...             ...
 32694  2025-12-26 00:00:00+07:00  2025-12-25T07:00:00+07:00             0.0
 32695  2025-12-26 00:00:00+07:00  2025-12-25T07:00:00+07:00             0.0
 32696  2025-12-26 00:00:00+07:00  2025-12-25T07:00:00+07:00             0.0
 32697  2025-12-26 00:00:00+07:00  2025-12-25T07:00:00+07:00            31.6
 32698  2025-12-26 00:00:00+07:00  2025-12-25T07:00:00+07:00             0.0

        tele_station_id tele_station_oldcode measure_datetime
 0                  345                 POCE       2025-12-20
 1                  762                 CHAM       2025-12-20
 2              1109494               ONE005       2025-12-20
 3                  286                 TSUD       2025-12-20
 4                  436                 DITO       2025-12-20
 ...                ...                  ...              ...
 32694              649                 SSRG       2025-12-25
 32695              534                 MCHI       2025-12-25
 32696              681                 PPTC       2025-12-25
 32697              898               VLGE42       2025-12-25
 32698           575566               BKC002       2025-12-25

 [32699 rows x 6 columns]}

In [25]:
import pandas as pd

# Concatenate all monthly DataFrames into a single DataFrame
all_2025_daily_rain = pd.concat(monthly_dfs.values(), ignore_index=True)

# Display the first 5 rows of the combined DataFrame
print("First 5 rows of the combined 2025 daily rain data:")
display(all_2025_daily_rain.head())

First 5 rows of the combined 2025 daily rain data:

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,station_code,value
0,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.2,447.0,THCG,2025-07-10,NaN,NaN
1,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.0,812.0,TPI004,2025-07-10,NaN,NaN
2,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,1.0,669.0,PPRM,2025-07-10,NaN,NaN
3,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.6,865.0,TNG002,2025-07-10,NaN,NaN
4,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.0,937.0,PNCR,2025-07-10,NaN,NaN

In [27]:
all_2025_daily_rain

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime,station_code,value
0,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.2,447.0,THCG,2025-07-10,NaN,NaN
1,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.0,812.0,TPI004,2025-07-10,NaN,NaN
2,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,1.0,669.0,PPRM,2025-07-10,NaN,NaN
3,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.6,865.0,TNG002,2025-07-10,NaN,NaN
4,2025-07-11 00:00:00+07:00,2025-07-11T07:00:00+07:00,0.0,937.0,PNCR,2025-07-10,NaN,NaN
...,...,...,...,...,...,...,...,...
180695,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,0.0,649.0,SSRG,2025-12-25,NaN,NaN
180696,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,0.0,534.0,MCHI,2025-12-25,NaN,NaN
180697,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,0.0,681.0,PPTC,2025-12-25,NaN,NaN
180698,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,31.6,898.0,VLGE42,2025-12-25,NaN,NaN
180699,2025-12-26 00:00:00+07:00,2025-12-25T07:00:00+07:00,0.0,575566.0,BKC002,2025-12-25,NaN,NaN

In [26]:
# Display the info of the combined DataFrame to check columns and data types
print("\nInfo of the combined 2025 daily rain data:")
all_2025_daily_rain.info()

Info of the combined 2025 daily rain data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180700 entries, 0 to 180699
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   rainfall_datetime       176886 non-null  object
 1   rainfall_datetime_calc  176886 non-null  object
 2   rainfall_value          176882 non-null  float64
 3   tele_station_id         173072 non-null  float64
 4   tele_station_oldcode    168021 non-null  object
 5   measure_datetime        180700 non-null  object
 6   station_code            3814 non-null    object
 7   value                   3814 non-null    float64
dtypes: float64(3), object(5)
memory usage: 11.0+ MB

In [17]:
stations_in_the_modle_hii = pd.read_csv('/content/drive/MyDrive/midtermdata/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/Stations in the model_HII.csv')
stations_in_the_modle_hii

       Node        Lat        Long
0      ACRU  15.788054  104.642235
1      BBHN   9.536913   98.579490
2      BBUA  17.372976  103.984436
3      BCNG  17.386840  103.290870
4      BDAR  14.587073  102.495190
..      ...        ...         ...
380  YOM003  18.265924  100.177060
381  YOM008  16.708166  100.171780
382  YOM009  16.310750  100.271750
383  YOM010  18.133717  100.124596
384  YOM012  17.021260   99.819710

[385 rows x 3 columns]

In [18]:
y_monthly_rain = pd.read_csv('/content/drive/MyDrive/midtermdata/BSC DPDM midterm 2025/Output - (Clean monthly rain - 2025)/Y_monthly_rain_HII_operation.csv')
y_monthly_rain

      Node   rain  month  year
0     ACRU   83.0      7  2025
1     ACRU  164.8      8  2025
2     ACRU  248.6      9  2025
3     ACRU   48.4     10  2025
4     ACRU   52.2     11  2025
5     ACRU    0.2     12  2025
6     BBHN  391.6      7  2025
7     BBHN  641.2      8  2025
8     BBHN  517.6      9  2025
9     BBHN  198.8     10  2025
10    BBHN  224.0     11  2025
11    BBHN    5.8     12  2025
12    BBUA  135.6      7  2025
13    BBUA   58.0      8  2025
14    BBUA   14.8      9  2025
15    BBUA   71.8     10  2025
16  YOM012  100.6     11  2025
17  YOM012    8.0     12  2025

#1. อ่านไฟล์ทั้งหมด แสดงโครงสร้างข้อมูล และอธิบายความหมาย

In [28]:
# 1.1 แสดงโครงสร้างข้อมูล (Shape) และตัวอย่างข้อมูล
print("=== Structure of Operational Data (2025) ===")
print(f"Shape: {all_2025_daily_rain.shape}")
print(all_2025_daily_rain.head())
print("\nInfo:")
print(all_2025_daily_rain.info())

print("\n=== Structure of Station Data ===")
print(f"Shape: {stations_in_the_modle_hii.shape}")
print(stations_in_the_modle_hii.head())

print("\n=== Structure of Historical Data (2012-2024) ===")
print(f"Shape: {hii_daily_rain.shape}")
print(hii_daily_rain.head())

=== Structure of Operational Data (2025) ===
Shape: (180700, 8)
           rainfall_datetime     rainfall_datetime_calc  rainfall_value  \
0  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.2
1  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.0
2  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             1.0
3  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.6
4  2025-07-11 00:00:00+07:00  2025-07-11T07:00:00+07:00             0.0

   tele_station_id tele_station_oldcode measure_datetime station_code  value
0            447.0                 THCG       2025-07-10          NaN    NaN
1            812.0               TPI004       2025-07-10          NaN    NaN
2            669.0                 PPRM       2025-07-10          NaN    NaN
3            865.0               TNG002       2025-07-10          NaN    NaN
4            937.0                 PNCR       2025-07-10          NaN    NaN

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180700 entries, 0 to 180699
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   rainfall_datetime       176886 non-null  object
 1   rainfall_datetime_calc  176886 non-null  object
 2   rainfall_value          176882 non-null  float64
 3   tele_station_id         173072 non-null  float64
 4   tele_station_oldcode    168021 non-null  object
 5   measure_datetime        180700 non-null  object
 6   station_code            3814 non-null    object
 7   value                   3814 non-null    float64
dtypes: float64(3), object(5)
memory usage: 11.0+ MB
None

=== Structure of Station Data ===
Shape: (385, 3)
   Node        Lat        Long
0  ACRU  15.788054  104.642235
1  BBHN   9.536913   98.579490
2  BBUA  17.372976  103.984436
3  BCNG  17.386840  103.290870
4  BDAR  14.587073  102.495190

=== Structure of Historical Data (2012-2024) ===
Shape: (3768463, 13)
  station_code        measure_datetime  data station_name   latitude  \
0         ABRT  2012-01-01 07:00:00+07   0.0   วัดเวฬุวัน  16.054785
1         ABRT  2012-01-03 07:00:00+07   0.0   วัดเวฬุวัน  16.054785
2         ABRT  2012-01-06 07:00:00+07   0.0   วัดเวฬุวัน  16.054785
3         ABRT  2012-01-07 07:00:00+07   0.0   วัดเวฬุวัน  16.054785
4         ABRT  2012-01-08 07:00:00+07   0.0   วัดเวฬุวัน  16.054785

   longitude quality_flag basin           sub_basin      tambon  \
0  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง
1  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง
2  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง
3  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง
4  103.66429            U    ชี  ลำน้ำชีส่วนที่ 4/2  เหนือเมือง

          amphoe  province       data_type
0  เมืองร้อยเอ็ด  ร้อยเอ็ด  rainfall_daily
1  เมืองร้อยเอ็ด  ร้อยเอ็ด  rainfall_daily
2  เมืองร้อยเอ็ด  ร้อยเอ็ด  rainfall_daily
3  เมืองร้อยเอ็ด  ร้อยเอ็ด  rainfall_daily
4  เมืองร้อยเอ็ด  ร้อยเอ็ด  rainfall_daily

'\nคำอธิบายคอลัมน์:\n- code / Node: รหัสสถานีตรวจวัดอากาศ (Key หลักในการเชื่อมข้อมูล)\n- date: วันที่ที่ทำการตรวจวัด (Format: YYYY-MM-DD)\n- rain: ปริมาณน้ำฝนที่วัดได้ (หน่วย: มิลลิเมตร)\n- Lat/Long: พิกัดภูมิศาสตร์ของสถานี\n'


คำอธิบายคอลัมน์:
- code / Node: รหัสสถานีตรวจวัดอากาศ (Key หลักในการเชื่อมข้อมูล)
- date: วันที่ที่ทำการตรวจวัด (Format: YYYY-MM-DD)
- rain: ปริมาณน้ำฝนที่วัดได้ (หน่วย: มิลลิเมตร)
- Lat/Long: พิกัดภูมิศาสตร์ของสถานี

#2. กรองข้อมูลให้เหลือเฉพาะสถานีใน stations in the model_hii.csv

In [30]:
# สร้าง list ของสถานีที่ต้องการ (Target Stations)
target_stations = stations_in_the_modle_hii['Node'].unique()

print(f"จำนวนสถานีที่มีในข้อมูลดิบ (2025): {all_2025_daily_rain['tele_station_oldcode'].nunique()} สถานี")

# กรองข้อมูล: เลือกเฉพาะ row ที่ column 'tele_station_oldcode' อยู่ใน target_stations
df_2025_filtered = all_2025_daily_rain[all_2025_daily_rain['tele_station_oldcode'].isin(target_stations)].copy()

print(f"จำนวนสถานีหลังจากกรองเหลือ: {df_2025_filtered['tele_station_oldcode'].nunique()} สถานี")
print(f"จำนวน Row ก่อนกรอง: {len(all_2025_daily_rain)} -> หลังกรอง: {len(df_2025_filtered)}")

จำนวนสถานีที่มีในข้อมูลดิบ (2025): 1514 สถานี
จำนวนสถานีหลังจากกรองเหลือ: 384 สถานี
จำนวน Row ก่อนกรอง: 180700 -> หลังกรอง: 66275

#3. ระบุข้อมูลสูญหาย (Missing Records) ของแต่ละสถานี

In [32]:
# สร้างช่วงเวลาเต็ม ตั้งแต่ 1 ก.ค. - 31 ธ.ค. 2025
full_date_range = pd.date_range(start='2025-07-01', end='2025-12-31', freq='D')

# แปลงคอลัมน์วันที่ใน df_2025_filtered ให้เป็น datetime object
df_2025_filtered['measure_datetime'] = pd.to_datetime(df_2025_filtered['measure_datetime'])

# แปลงข้อมูลเป็น Pivot Table เพื่อให้เห็นช่องว่างง่ายๆ (Index=Date, Column=Station)
# ถ้าวันไหนไม่มีข้อมูล ค่าจะเป็น NaN โดยอัตโนมัติ
df_pivot = df_2025_filtered.pivot_table(index='measure_datetime', columns='tele_station_oldcode', values='rainfall_value')

# Reindex ด้วยช่วงเวลาเต็ม เพื่อให้เห็นวันที่หายไปทั้งแถว (ถ้ามี)
df_pivot = df_pivot.reindex(full_date_range)

# นับจำนวนข้อมูลที่หายไป (NaN) ในแต่ละสถานี
missing_count = df_pivot.isnull().sum()
total_days = len(full_date_range) # 184 วัน

# คำนวณสัดส่วน % ที่หายไป
missing_percent = (missing_count / total_days) * 100

# สร้าง Dataframe สรุปผล
missing_summary = pd.DataFrame({
    'Missing_Records': missing_count,
    'Percent_Missing': missing_percent
})

print("=== สรุปข้อมูลสูญหายแต่ละสถานี (ตัวอย่าง 10 สถานีแรก) ===")
print(missing_summary.head(10))

=== สรุปข้อมูลสูญหายแต่ละสถานี (ตัวอย่าง 10 สถานีแรก) ===
                      Missing_Records  Percent_Missing
tele_station_oldcode
ACRU                                0         0.000000
BBHN                                0         0.000000
BBUA                               15         8.152174
BCNG                                0         0.000000
BDAR                                0         0.000000
BDCP                                1         0.543478
BDGN                                0         0.000000
BDLH                                0         0.000000
BDMG                                0         0.000000
BGRT                                0         0.000000

#4. คัดสถานีที่ข้อมูลสูญหาย >= 20% ออก

In [33]:
# หา list รายชื่อสถานีที่ต้องตัดทิ้ง (Missing >= 20%)
stations_to_drop = missing_summary[missing_summary['Percent_Missing'] >= 20].index.tolist()

# หา list รายชื่อสถานีที่จะเก็บไว้ (Missing < 20%)
stations_to_keep = missing_summary[missing_summary['Percent_Missing'] < 20].index.tolist()

print(f"จำนวนสถานีทั้งหมด: {len(missing_summary)}")
print(f"ถูกคัดออก (>=20% missing): {len(stations_to_drop)} สถานี")
print(f"คงเหลือ: {len(stations_to_keep)} สถานี")

print("\nรายชื่อสถานีที่ถูกคัดออก:", stations_to_drop)

# กรองข้อมูล Pivot Table ให้เหลือเฉพาะสถานีที่เก็บไว้
df_clean_pivot = df_pivot[stations_to_keep].copy()

จำนวนสถานีทั้งหมด: 384
ถูกคัดออก (>=20% missing): 45 สถานี
คงเหลือ: 339 สถานี

รายชื่อสถานีที่ถูกคัดออก: ['BKHN', 'BKK017', 'BLKO', 'BNGR', 'BNLG', 'BPTG', 'BSKJ', 'BSPN', 'CEHM', 'CGKM', 'CHI010', 'CHI013', 'CHNA', 'CPY010', 'CTKN', 'DCCT', 'DGSL', 'KKTO', 'KON005', 'LMSK', 'MEWG', 'MMMO', 'MNRM', 'NAPK', 'NASW', 'NEAK', 'NGCG', 'NGPI', 'NKSG', 'NNPT', 'NPI002', 'PAS008', 'PMPN', 'PRN001', 'PSLT', 'SGKW', 'SKE001', 'SKM004', 'SLA002', 'TPI007', 'TUKW', 'VLGE33', 'WAN005', 'YCUM', 'YOM001']

#5. เติมข้อมูลที่หายไปด้วยค่า Median ตาม Day of Year จาก Historical

In [35]:
# --- 5.1 เตรียมข้อมูล Historical ---
# แปลง measure_datetime เป็น datetime
hii_daily_rain['measure_datetime'] = pd.to_datetime(hii_daily_rain['measure_datetime'])
# สร้าง column Day of Year (1-366)
hii_daily_rain['DOY'] = hii_daily_rain['measure_datetime'].dt.dayofyear

# คำนวณ Median แยกตาม 'station_code' และ 'DOY'
historical_median = hii_daily_rain.groupby(['station_code', 'DOY'])['data'].median().reset_index()
historical_median.rename(columns={'data': 'median_rain', 'station_code': 'code'}, inplace=True)

# --- 5.2 เติมข้อมูลลงใน df_clean_pivot ---
# แปลง Pivot กลับมาเป็นตารางยาว (Melt/Stack) เพื่อให้จัดการง่าย
df_filled = df_clean_pivot.stack(dropna=False).reset_index()
# หลังจาก stack และ reset_index คอลัมน์จะเป็น 'measure_datetime', 'tele_station_oldcode' และ 'rainfall_value'
# เราจะเปลี่ยนชื่อคอลัมน์เหล่านี้เพื่อให้ตรงกับที่เราต้องการ ('date', 'code', 'rain')
df_filled.columns = ['date', 'code', 'rain']

# เพิ่ม column DOY ให้ข้อมูลปี 2025
df_filled['DOY'] = df_filled['date'].dt.dayofyear

# Merge ข้อมูล Median เข้ามา (เหมือน VLOOKUP)
df_filled = pd.merge(df_filled, historical_median, on=['code', 'DOY'], how='left')

# เติมค่า NaN ใน column 'rain' ด้วยค่าจาก 'median_rain'
df_filled['rain'] = df_filled['rain'].fillna(df_filled['median_rain'])

# ตรวจสอบว่ายังมีค่าหายไปไหม
missing_after_fill = df_filled['rain'].isnull().sum()
print(f"จำนวน Record ที่ยังเป็น NaN หลังเติมข้อมูล: {missing_after_fill}")

# (Optional) ถ้ายังมี NaN (เพราะ Historical ก็ไม่มีข้อมูลวันนั้น) อาจเติมด้วย 0 หรือค่าเฉลี่ยรวม
if missing_after_fill > 0:
    df_filled['rain'] = df_filled['rain'].fillna(0)
    print("เติม NaN ที่เหลือด้วย 0 เรียบร้อย")

จำนวน Record ที่ยังเป็น NaN หลังเติมข้อมูล: 0

/tmp/ipython-input-3408985508.py:13: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_filled = df_clean_pivot.stack(dropna=False).reset_index()

#6. บอกเหตุผลที่ใช้ Median แทน Mean

**เหตุผลที่ใช้ Median (มัธยฐาน) แทน Mean (ค่าเฉลี่ย):**

1.  **การแจกแจงข้อมูลน้ำฝน (Skewed Distribution):** ข้อมูลปริมาณน้ำฝนส่วนใหญ่มักเป็น 0 ในวันที่ฝนไม่ตก และมีบางวันที่ค่าสูงมาก ในวันที่พายุเข้า ทำให้กราฟเบ้ขวาอย่างมาก
2.  **ผลกระทบจากค่าผิดปกติ (Outliers):** ค่า Mean จะถูกดึงด้วยค่าฝนที่ตกหนักผิดปกติ (Extreme values) ทำให้ค่าที่ได้สูงเกินความเป็นจริงของวันปกติ
3.  **ตัวแทนที่ดีกว่า:** Median คือค่าที่อยู่ตรงกลางจริงๆ จึงเป็นตัวแทนที่เหมาะสมกว่าในการระบุว่าโดยปกติแล้ว ในวันนี้ของปี ฝนมักจะตกประมาณเท่าไหร่

#7. คำนวณผลรวมปริมาณน้ำฝนรายเดือน และจัดรูปแบบ Output

In [36]:
# สร้าง column month และ year จาก date
df_filled['month'] = df_filled['date'].dt.month
df_filled['year'] = df_filled['date'].dt.year

# คำนวณผลรวมรายเดือน (Groupby Station, Month, Year)
monthly_rain = df_filled.groupby(['code', 'month', 'year'])['rain'].sum().reset_index()

# เปลี่ยนชื่อ column 'code' เป็น 'Node' ให้ตรงตามโจทย์
monthly_rain.rename(columns={'code': 'Node'}, inplace=True)

# จัดลำดับ Column ให้ตรงตามไฟล์ตัวอย่าง (Node, rain, month, year)
output_df = monthly_rain[['Node', 'rain', 'month', 'year']]

# แสดงผลลัพธ์
print("=== ตัวอย่างผลลัพธ์รายเดือน (5 แถวแรก) ===")
print(output_df.head())

# บันทึกไฟล์ (Optional)
# output_df.to_csv('output_monthly_rainfall.csv', index=False)

=== ตัวอย่างผลลัพธ์รายเดือน (5 แถวแรก) ===
   Node   rain  month  year
0  ACRU   83.0      7  2025
1  ACRU  164.8      8  2025
2  ACRU  248.6      9  2025
3  ACRU   48.4     10  2025
4  ACRU   52.2     11  2025

In [37]:
output_df

        Node   rain  month  year
0       ACRU   83.0      7  2025
1       ACRU  164.8      8  2025
2       ACRU  248.6      9  2025
3       ACRU   48.4     10  2025
4       ACRU   52.2     11  2025
...      ...    ...    ...   ...
2029  YOM012  149.8      8  2025
2030  YOM012  256.0      9  2025
2031  YOM012   30.0     10  2025
2032  YOM012  100.6     11  2025
2033  YOM012    8.0     12  2025

[2034 rows x 4 columns]

In [38]:
output_df.to_csv('/content/drive/MyDrive/output_monthly_rainfall.csv', index=False)
print("ไฟล์ 'output_monthly_rainfall.csv' ถูกบันทึกเรียบร้อยแล้วใน Google Drive ของคุณ!")

ไฟล์ 'output_monthly_rainfall.csv' ถูกบันทึกเรียบร้อยแล้วใน Google Drive ของคุณ!

#ไฟล์ output ผลลัพธ์สุดท้าย

https://drive.google.com/file/d/1WhUI3z-I8YBSCfldTXYo5TPnVdhfcQ8K/view?usp=sharing

#ไฟล์promptที่ใช้

https://docs.google.com/document/d/1i54Lx37arygH2xj71hVz3uPoQvVgZqTE/edit?usp=sharing&ouid=112099582175020236783&rtpof=true&sd=true